# Generated by Django 2.1.7 on 2019-03-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_auto_20190318_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='dish.DishTypes'),
        ),
    ]
