# Generated by Django 2.1.7 on 2019-03-18 13:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('dish', '0004_auto_20190318_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishTypes',
            new_name='DishType',
        ),
    ]
