# Generated by Django 2.1.7 on 2019-03-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_auto_20190318_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.DishType'),
        ),
    ]
