# Generated by Django 2.1.7 on 2019-03-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_auto_20190318_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
