# Generated by Django 2.1.7 on 2019-03-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0007_dish_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishtype',
            name='generic_price',
            field=models.FloatField(default=0.0),
        ),
    ]
