# Generated by Django 2.1.7 on 2019-04-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0009_auto_20190423_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='provider',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dish.Provider'),
        ),
    ]
